# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlightObserver' do
  use_frameworks!

  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire', '~> 5.4'
  pod 'ImageSlideshow', '~> 1.9.0'

end
